[build]
  command = "npm run build"
  publish = "dist"

# Force le comportement SPA si vous préférez configurer ici plutôt qu'avec /public/_redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
